apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-kbga
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jhutar-tenant/my-app/devfile-sample-python-basic-kbga@sha256:888652a4e2fbeaf2a2c816e75a84265bc6a6d0ef7f3255de99c116ea29f2b299
        name: my-python
        resources: {}
status: {}
